

version: "3.9"
services:

  db:
    image: postgres:14.3-alpine3.15
    ports:
      - "5431:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      
  pg_admin:
    image: "dpage/pgadmin4:latest"
    ports:
      - 7070:80
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@yandex.ru"
      PGADMIN_DEFAULT_PASSWORD: "admin1pwd"
      PGADMIN_DEFAULT_CONFIG_SERVER_MODE: "False"
